project:
  type: book

book:
  title: "Homework 2"
  subtitle: "Exercise 3 and 6"
  author: "Vincent Xie"
  date: "1/29/2024"
  chapters:
    - exercise3.qmd


format:
  pdf:
   documentclass: scrreprt

execute:
  freeze: auto